package.json
and let webpack auto-detect.
As suggested at https://github.com/webpack/webpack/issues/12598#issuecomment-774010358
Fixes: GH-237
=> build: package.json: Remove "type": "commonjs"

src/defs.ts
Fixes this issue: https://github.com/47ng/next-usequerystate/issues/329
=> prevent empty string while setting an empty array as value

packages/next-usequerystate/src/defs.ts
=> fix(#368): replace next/navigation with next/navigation.js

package.json, packages/next-usequerystate/package.json, packages/playground/package.json, pnpm-lock.yaml
Everything seems in order. Happy Next.js conf everyone!
(Not a bug fix, I should setup semrel to support arbitrary patch updates one day).
=> fix(deps): Add Next.js 14 support

README.md
@franky47  close https://github.com/47ng/next-usequerystate/issues/414
=> docs: improve supported version information

packages/e2e/cypress/e2e/hash-preservation.cy.js, packages/nuqs/src/update-queue.ts
=> fix: Hash preservation

.github/workflows/ci-cd.yml, .github/workflows/test-against-nextjs-release.yml
Reusing configs from .node-version and packageManager in package.json.
See:
https://x.com/sitnikcode/status/1791437686076579978
=> chore: Smarter CI setup

.github/workflows/ci-cd.yml, packages/docs/package.json, pnpm-lock.yaml
Thanks @QuiiBz for this nice tool! - https://github.com/QuiiBz/sherif
=> chore: Lint monorepo with Sherif

.github/workflows/pkg.pr.new.yml
Now we need someone to open a PR so I can test this 😅
=> chore: Add pkg.pr.new to preview PRs outside of NPM

.github/workflows/pkg.pr.new.yml
Testing GitHub's new UI to surface annotations
=> chore: Annotate deployment job

packages/e2e/cypress/e2e/repro-702.cy.js, packages/e2e/src/app/app/repro-702/page.tsx, packages/nuqs/src/update-queue.ts, packages/nuqs/src/useQueryState.ts, packages/nuqs/src/useQueryStates.ts
=> fix: Read queued updates when initialising state

errors/NUQS-101.md, packages/docs/content/docs/testing.mdx, packages/nuqs/esm-only.cjs
=> doc: Add Jest guidelines & ESM-only error page

packages/docs/package.json, packages/docs/src/app/(pages)/_landing/footer.tsx, packages/e2e/react-router/package.json, packages/e2e/react/package.json, packages/e2e/remix/package.json, packages/nuqs/package.json, pnpm-lock.yaml
🦋 https://bsky.app/profile/nuqs.47ng.com
=> doc: Update socials: bye X, RIP Twitter, hello Bluesky

packages/e2e/next/cypress/e2e/repro-758.cy.js, packages/e2e/next/src/app/app/repro-758/page.tsx, packages/nuqs/src/useQueryStates.ts
=> fix: Use correct keys for state sync

packages/nuqs/package.json
=> fix: Add React 19 RC in peer dep semver range

packages/nuqs/src/useQueryState.ts
=> fix: Protection against null useSearchParams in Next.js

packages/nuqs/src/url-encoding.test.ts, packages/nuqs/src/url-encoding.ts
=> fix: Encode invisible ASCII control characters

packages/e2e/next/cypress/e2e/shared/form.cy.ts, packages/e2e/next/src/app/app/(shared)/form/useQueryState/page.tsx, packages/e2e/next/src/app/app/(shared)/form/useQueryStates/page.tsx, packages/e2e/next/src/pages/pages/form/useQueryState.tsx, packages/e2e/next/src/pages/pages/form/useQueryStates.tsx, packages/e2e/react-router/v6/cypress/e2e/shared/form.cy.ts, packages/e2e/react-router/v6/src/react-router.tsx, packages/e2e/react-router/v6/src/routes/form.useQueryState.tsx, packages/e2e/react-router/v6/src/routes/form.useQueryStates.tsx, packages/e2e/react-router/v7/app/routes.ts, packages/e2e/react-router/v7/app/routes/form.useQueryState.tsx, packages/e2e/react-router/v7/app/routes/form.useQueryStates.tsx, packages/e2e/react-router/v7/cypress/e2e/shared/form.cy.ts, packages/e2e/react/cypress/e2e/shared/form.cy.ts, packages/e2e/react/src/routes.tsx, packages/e2e/react/src/routes/form.useQueryState.tsx, packages/e2e/react/src/routes/form.useQueryStates.tsx, packages/e2e/remix/app/routes/form.useQueryState.tsx, packages/e2e/remix/app/routes/form.useQueryStates.tsx, packages/e2e/remix/cypress/e2e/shared/form.cy.ts, packages/e2e/shared/specs/form.cy.ts, packages/e2e/shared/specs/form.tsx
=> test: Add native HTML form test

packages/nuqs/package.json, pnpm-lock.yaml
See https://github.com/47ng/nuqs/issues/726#issuecomment-2568932338.
=> chore: Update version range to include react-router@^6

packages/nuqs/src/index.server.ts, packages/nuqs/src/index.ts
Forgot to export it from the barrel files 😬
=> fix: Export UrlKeys type helper

.github/workflows/analyse-nextjs-release.yml, .github/workflows/ci-cd.yml, .github/workflows/milestone-automation.yml, .github/workflows/pkg.pr.new.yml, .github/workflows/pr-base-enforcement.yml, .github/workflows/ship-it.yml, .github/workflows/snapshot-release.yml, .github/workflows/test-against-nextjs-release.yml
Testing @lkfortuna's tip to see if it fixes the actions/checkout random crashes.
=> chore: Trying ubuntu-22.04-arm runners

packages/docs/src/app/(pages)/react-paris/link-tree.tsx, packages/docs/src/app/(pages)/react-paris/page.tsx
https://react.paris/ - 2025-03-20 at 15:00 Europe/Paris
=> doc: Add link tree for React Paris

packages/docs/src/app/(pages)/_landing/footer.tsx, packages/docs/src/app/banners.tsx, packages/docs/src/app/docs/layout.tsx, packages/docs/src/app/layout.tsx, packages/docs/src/app/playground/layout.tsx
=> doc: React Paris is over 😥

packages/nuqs/src/adapters/next/app.ts, packages/nuqs/src/adapters/react.ts
From feedback by @TkDodo in https://github.com/47ng/nuqs/pull/1079#discussion_r2287880913.
=> chore: Pass children as config in createElement to avoid ts-expect-error

packages/nuqs/src/adapters/testing.ts, packages/nuqs/src/useQueryState.test.ts, packages/nuqs/src/useQueryStates.test.ts
=> fix: Referential stability for the testing adapter

packages/docs/content/docs/parsers/community/meta.json, packages/docs/content/docs/parsers/community/zod-codecs-demo.tsx, packages/docs/content/docs/parsers/community/zod-codecs.demo.tsx, packages/docs/content/docs/parsers/community/zod-codecs.lib.ts, packages/docs/content/docs/parsers/community/zod-codecs.mdx, packages/docs/content/docs/parsers/community/zod-codecs.skeleton.tsx, packages/docs/content/docs/parsers/community/zod-codecs.source.tsx, packages/docs/package.json, packages/docs/src/app/(pages)/stats/lib/npm.ts, packages/docs/src/components/ui/input.tsx, packages/nuqs/package.json, packages/scripts/package.json, pnpm-lock.yaml
From the video: https://www.youtube.com/watch?v=k4lWvklUxUE
=> doc: Add Zod codecs community parsers

.github/workflows/ci-cd.yml, .github/workflows/test-against-nextjs-release.yml, CONTRIBUTING.md, README.md, errors/NUQS-101.md, errors/NUQS-303.md, errors/NUQS-404.md, errors/NUQS-414.md, errors/NUQS-422.md, packages/docs/content/blog/nuqs-2.5.mdx, packages/docs/next.config.mjs, packages/docs/src/app/(pages)/_landing/page-footer.tsx, packages/docs/src/app/(pages)/blog/[slug]/page.tsx, packages/docs/src/app/(pages)/blog/rss.xml/route.ts, packages/docs/src/app/(pages)/page.tsx, packages/docs/src/app/(pages)/react-paris/page.tsx, packages/nuqs/package.json, packages/nuqs/src/lib/errors.ts, packages/nuqs/src/lib/queues/throttle.test.ts
=> doc: Move to nuqs.dev

packages/docs/src/app/docs/[[...slug]]/page.tsx, packages/docs/src/app/robots.ts, packages/docs/src/app/sitemap.ts, packages/docs/src/lib/url.ts
Maybe drop all of this and use https://www.npmjs.com/package/next-sitemap
A validator that doesn't suck: https://ismywebsiteready.com/tools/sitemap-xml-validator
=> doc: Add sitemap
