- src/app/demos/repro-359/page.tsx
- src/app/page.tsx
- src/lib/update-queue.ts
- src/lib/useQueryState.ts
- src/lib/useQueryStates.ts
This solves issues when a component is mounted by a state change, and which itself contains a hook on the key that caused it to mount.
Because the correct value is still in the queue at mount time, it won't be correctly set in the mounted component, and because internal history updates don't trigger a state sync, the newly mounted component won't re-render when the URL is updated.
[Reproduction in the playground](https://next-usequerystate-git-fix-359-initial-state-from-queue-47ng.vercel.app/demos/repro-359)
Closes #359.
> fix: Consider queued updates for initial state

- .github/workflows/ci-cd.yml
- packages/next-usequerystate/src/parsers.test.ts
- packages/next-usequerystate/src/parsers.ts
- packages/next-usequerystate/src/update-queue.ts
- packages/next-usequerystate/src/url-encoding.test.ts
- packages/next-usequerystate/src/url-encoding.ts
- packages/playground/src/app/demos/compound-parsers/page.tsx
- packages/playground/src/app/demos/custom-parser/page.tsx
- packages/playground/src/app/page.tsx
Don't URL-encode safe characters, and fix the array parser logic.
Proposed encoding, compared with built-in solutions:
```
┌──────┬──────────────────┬────────────────┬────────────────────┐
│ char │ encodeQueryValue │ encodeURI      │ encodeURIComponent │
├──────┼──────────────────┼────────────────┼────────────────────┤
│  !   │   !              │   !            │   !                │
│  "   │          %22     │          %22   │          %22       │
│  #   │          %23     │   #            │          %23       │
│  $   │   $              │   $            │          %24       │
│  %   │          %25     │          %25   │          %25       │
│  &   │          %26     │   &            │          %26       │
│  '   │          %27     │   '            │   '                │
│  (   │   ( …
```
> feat: Prettify URLs

- packages/next-usequerystate/src/parsers.test.ts
- packages/next-usequerystate/src/parsers.ts
When using a string parser with a default value, it wasn't properly handled due to an incorrect default assignment to an empty string to satisfy TypeScript.
Closes #384.
> fix: Default value on server-side parsing

- README.md
- packages/next-usequerystate/src/parsers.test.ts
- packages/next-usequerystate/src/parsers.ts
- packages/next-usequerystate/src/tests/parsers.test-d.ts
- packages/next-usequerystate/src/tests/useQueryState.test-d.ts
- packages/playground/src/app/demos/server-side-parsing/client.tsx
Rather than adding another method, extend the types to allow chaining options and setting default values regardless of order.
Runtime was mostly fine except for a bug where re-setting a default value would not work for server-side parsing.
Closes #386.
> feat: Allow chaining parser options & default values

- packages/e2e/cypress.config.ts
- packages/e2e/src/pages/pages/useQueryState/dynamic/[route]/index.tsx
- packages/e2e/src/pages/pages/useQueryState/index.tsx
- packages/next-usequerystate/src/update-queue.ts
- turbo.json
This fixes non-shallow updates for pages in the `pages` directory.
Closes #282.
> Fix non-shallow dynamic pages

- .github/workflows/ci-cd.yml
- .github/workflows/test-against-nextjs-release.yml
- packages/e2e/cypress.config.ts
- packages/e2e/cypress/e2e/internals.cy.js
- packages/e2e/cypress/e2e/repro-388.cy.js
- packages/e2e/next.config.mjs
- packages/e2e/package.json
- packages/e2e/src/app/app/internals/page.tsx
- packages/next-usequerystate/src/update-queue.ts
- packages/next-usequerystate/src/useQueryState.ts
- pnpm-lock.yaml
- turbo.json
Starting from next@14.0.3-canary.6, you can turn on the experimental `windowHistorySupport` flag to solve issues with prefetch links.
There may be some optimisations to do since Next.js now also patches the history methods (and do so after nuqs), so it looks like there isn't a need for external sync anymore, but this first draft seems to work.
Adding a few more CI cases to test for non-regression.
Note: raw canary (without the flag) still fails due to prefetch reset (see #388), so PR https://github.com/vercel/next.js/pull/58297 is still much needed there. But now at leas the flag gives us an escape hatch.
> feat: Add support for experimental WHS

- README.md
- packages/next-usequerystate/src/debug.ts
* Change the debugging logging from `console.debug` to `console.log` so logging is visible without changing the log level to "verbose"
* Simplify readme wording in the debug section
> Switch debug logging to `console.log`

- .github/ISSUE_TEMPLATE/bug_report.md
The checkboxes will show up as "tasks" on the issue summary "1 of 2 tasks done" wich is misleading since they are not tasks.
(https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md)
> bug_report template: Use emoji as checkboxes

- .github/workflows/ci-cd.yml
- README.md
- packages/next-usequerystate/package.json
This is to be released when next@14.0.3 lands.
> fix: Restore compatibility with next@latest

- .github/ISSUE_TEMPLATE/config.yml
This will expand the UI on the new issues screen to direct users to use the discussion for feature requests.
You can see how that looks for example here https://github.com/openstreetmap/iD/issues/new/choose ([Template](https://github.com/openstreetmap/iD/blob/develop/.github/ISSUE_TEMPLATE/config.yml))
> Github: Add links to discussion to new issue screen

- README.md
- packages/playground/src/app/demos/basic-counter/page.tsx
- packages/playground/src/app/demos/batching/page.tsx
- packages/playground/src/app/demos/builder-pattern/page.tsx
- packages/playground/src/app/demos/compound-parsers/page.tsx
- packages/playground/src/app/demos/crosslink/page.tsx
- packages/playground/src/app/demos/custom-parser/page.tsx
- packages/playground/src/app/demos/hex-colors/page.tsx
- packages/playground/src/app/demos/parsers/page.tsx
- packages/playground/src/app/demos/pretty-urls/page.tsx
- packages/playground/src/app/demos/repro-359/page.tsx
- packages/playground/src/app/demos/repro-376/page.tsx
- packages/playground/src/app/demos/server-side-parsing/page.tsx
- packages/playground/src/app/demos/subscribeToQueryUpdates/page.tsx
- packages/playground/src/app/demos/throttling/page.tsx
'Source on GitHub' urls in each demo broke as a result of moving files to support the monorepo:
I updated the urls to files in the playground folder.
Urls point to the correct files in the repo.
> fix: 'Source on GitHub' urls

- README.md
- packages/e2e/cypress/e2e/transitions.cy.js
- packages/e2e/src/app/app/transitions/client.tsx
- packages/e2e/src/app/app/transitions/page.tsx
- packages/next-usequerystate/src/defs.ts
- packages/next-usequerystate/src/parsers.ts
- packages/next-usequerystate/src/tests/parsers.test-d.ts
- packages/next-usequerystate/src/tests/useQueryState.test-d.ts
- packages/next-usequerystate/src/update-queue.test.ts
- packages/next-usequerystate/src/update-queue.ts
- packages/next-usequerystate/src/useQueryState.ts
- packages/next-usequerystate/src/useQueryStates.ts
- packages/playground/src/app/demos/throttling/client.tsx
This lets non-shallow updates be notified of server rendering loading status, using an external `React.useTransition` hook.
Example usage:
```tsx
function ClientComponent() {
// 1. Provide your own useTransition hook:
const [isLoading, startTransition] = React.useTransition()
const [query, setQuery] = useQueryState(
'query',
// 2. Pass the `startTransition` as an option:
parseAsString().withOptions({ startTransition })
)
// 3. isLoading will be true while the server is re-rendering and streaming RSC payloads
// when the query is updated via `setQuery`.
}
```
Things that need to be ironed out:
What happens if we were to call a `startTransition` on an unmounted component? Because the URL update is deferred, a query state update may cause the calling component to be unmounted, and its …
> feat: Add support for transitions

- README.md
- packages/next-usequerystate/src/sync.ts
It was broken in Next.js 14.0.3 due to shallow updates not calling the patched history methods, and fixed in Next.js 14.0.4.
However, since turning on the `windowHistorySupport` flag causes `useSearchParams` to be reactive to shallow URL query changes, there's no longer need for this method.
Marking it as deprecated now, and will be dropped along with other deprecations in v2.0.0 once WHS lands in GA.
Closes #422.
> fix: Deprecate `subscribeToQueryUpdates`

- packages/e2e/cypress/e2e/rewrites.cy.js
- packages/e2e/next.config.mjs
- packages/e2e/src/app/app/rewrites/destination/client.tsx
- packages/e2e/src/app/app/rewrites/destination/page.tsx
- packages/e2e/src/app/app/rewrites/destination/searchParams.ts
There are definitely some caveats to look out for when using rewrites with search params.
One is that the server and client search params on the rewritten page may differ, as the client will always see the source search params, but only the server can see additional search params injected by the rewrite rule.
Adding tests to showcase the baseline behaviour, which seems logical once you start thinking about where rewrites sit in the request/response cycle.
> test: Support for rewrites

- .github/workflows/ci-cd.yml
- README.md
- packages/next-usequerystate/scripts/mirror.sh
Mirroring package publishing to both `next-usequerystate` and `nuqs` until the next major, where `next-usequerystate` will no longer update.
> Rebranding to `nuqs`

- packages/nuqs/src/parsers.ts
- packages/nuqs/src/useQueryState.ts
- packages/nuqs/src/useQueryStates.ts
- packages/nuqs/src/utils.ts
- Fix actual printout (wrong interpolation)
- Improve DX by printing which key failed to parse
> fix: Safe parse everywhere

- README.md
- packages/docs/content/docs/index.mdx
- packages/nuqs/src/parsers.ts
Hello, while testing with the package I noticed that there is no support for as const string arrays.
Since I am one of those people who don't like enums, these are better for me to use.
I thought this parser might be interesting for everyone.
I have also extended the documentation and adapted outdated documentation for parseAsStringEnum.
> feat: Add literal parsers

- packages/nuqs/src/update-queue.ts
In test environment where Next.js isn't actually used but the router is mocked, this internal property isn't set, and accessing it causes a "Type error: cannot read properties of undefined (reading 'router')" error.
Closes #454.
> fix: Check for undefined `next` property on window

- packages/nuqs/package.json
- packages/nuqs/scripts/prepack.sh
- packages/nuqs/tsup.config.ts
BREAKING CHANGE: drop CJS support.
Since Next has ESM support since v12, it should not really be a breaking change for most.
> chore: ESM only (drop CJS support)

- .github/workflows/ci-cd.yml
- packages/e2e/cypress/e2e/repro-359.cy.js
- packages/e2e/src/app/app/repro-359/page.tsx
- packages/nuqs/src/update-queue.ts
- packages/nuqs/src/useQueryState.ts
Regression introduced by #457 was detected in the repro-359 test case, where components with a `useQueryState` failed to capture the correct value on mount, and trailed behind.
The `useEffect` introduced in #394 to sync internal state against a reactive `useSearchParams` hook in order to support WHS in 14.0.3 had a flaw. Actually, 14.0.3 had a flaw too, but we'll come to that in a bit.
The test in #359 exposes differences between the internal state of the `useQueryState` hook and the URL state (as reflected in a reactive `useSearchParams`): when a component mounts because of a query state change, and that component also listens for the same query key, its internal state will be fine on mount (due to the state initialisation function taking into account the URL update queue), but the …
> fix: Regression in mounting components

- packages/nuqs/src/update-queue.ts
- packages/nuqs/src/useQueryState.ts
> fix: Mark global `next` internal as optional

- .github/workflows/ci-cd.yml
- packages/docs/src/app/api/isr/route.ts
- packages/docs/src/app/docs/layout.tsx
Because the Vercel deployment happens in parallel with CI/CD which publishes to NPM, it always shows a stale version.
> doc: Enable ISR invalidation for latest version

- .github/workflows/ci-cd.yml
- packages/e2e/cypress.config.ts
- packages/e2e/cypress/e2e/useSearchParams.cy.js
- packages/e2e/src/app/app/useSearchParams/page.tsx
- packages/nuqs/src/update-queue.ts
- pnpm-lock.yaml
Set the history state to `null` as recommended in the Next.js docs for shallow routing.
Historically, while Next.js didn't support shallow routing (<14.1.0), maintaining the history state was the way to keep the app router state.
Closes #481.
> fix: Shallow state

- README.md
- errors/NUQS-500.md
- packages/docs/content/docs/index.mdx
- packages/docs/src/app/playground/(demos)/pagination/page.tsx
- packages/docs/src/app/playground/(demos)/pagination/searchParams.ts
- packages/docs/src/app/playground/_demos/server-side-parsing/parser.ts
- packages/docs/src/app/playground/_demos/throttling/parsers.ts
- packages/e2e/src/app/app/cache/searchParams.ts
- packages/e2e/src/app/app/push/searchParams.ts
- packages/e2e/src/app/app/rewrites/destination/page.tsx
- packages/e2e/src/app/app/rewrites/destination/searchParams.ts
- packages/e2e/src/app/app/routing-tour/_components/parsers.ts
- packages/nuqs/package.json
- packages/nuqs/server.d.ts
- packages/nuqs/src/index.parsers.ts
- packages/nuqs/src/index.server.ts
- packages/nuqs/tsup.config.ts
In preparation for v2.0.0 move, might as well give folks time to update.
> chore: Alias nuqs/server to nuqs/parsers

- packages/docs/content/docs/basic-usage.mdx
- packages/docs/content/docs/options.mdx
- packages/e2e/cypress/e2e/clearOnDefault.cy.js
- packages/e2e/src/app/app/clearOnDefault/page.tsx
- packages/nuqs/src/defs.ts
- packages/nuqs/src/update-queue.ts
- packages/nuqs/src/useQueryState.ts
- packages/nuqs/src/useQueryStates.ts
Adds an option to remove the key-value pair when setting a state to the default value. Default behaviour remains to keep it explicitly set in the URL, for backwards-compatibility when defaults change.
Closes #320.
Closes #488.
Closes #490.
> feat: Add "clear on default" option

- package.json
- packages/docs/package.json
- patches/next@14.1.1-canary.0.patch
- pnpm-lock.yaml
Using `next@14.1.1-canary.0` as the base for the docs in order to patch it without breaking the e2e test playground.
> chore: Fix anchor nav in docs breaking interactive demos

- .github/workflows/test-against-nextjs-release.yml
- packages/scripts/next-release-analyser.mjs
- packages/scripts/package.json
- packages/scripts/tsconfig.json
- pnpm-lock.yaml
Having an email on every canary release can be too verbose, I'm only interested in being notified of releases that change the app router core code, which may impact `nuqs`.
> chore: Analyse Next.js releases for app router changes

- packages/e2e/cypress/e2e/clearOnDefault.cy.js
- packages/e2e/src/app/app/clearOnDefault/page.tsx
- packages/nuqs/package.json
- packages/nuqs/src/parsers.test.ts
- packages/nuqs/src/parsers.ts
- packages/nuqs/src/useQueryState.ts
- packages/nuqs/src/useQueryStates.ts
As reported by @Kavan72 in https://github.com/47ng/nuqs/discussions/462#discussioncomment-8554053
Testing only for referential equality is not enough for types like arrays and objects.
This introduces a new property of the parsers to specify an equality function to use when comparing against the default value.
> fix: Equality check for non-primitives in clearOnDefault

- packages/e2e/cypress/e2e/repro-542.cy.js
- packages/e2e/src/app/app/repro-542/a/page.tsx
- packages/e2e/src/app/app/repro-542/b/page.tsx
- packages/e2e/src/app/app/repro-542/client.tsx
- packages/nuqs/src/useQueryState.ts
- packages/nuqs/src/useQueryStates.ts
This makes the first render on client side navigation use the source URL rather than the destination, which can cause issues if the first state is memoised or used for some other purposes.
useSearchParams contains the destination values for searchParams, however this might break in older versions of Next.js (TBC by CI). In which case this fix might only land on v2.
Closes #542.
> fix: Don't rely on URL for initial state

- packages/e2e/cypress/e2e/cache.cy.js
- packages/nuqs/src/cache.test.ts
- packages/nuqs/src/cache.ts
- packages/nuqs/src/index.server.ts
A change introduced in Next.js 15.0.0-canary.41 (precisely vercel/next.js#67105) broke the referential stability that the cache.parse method was expecting to detect `parse` being called with the same search params.
Now we're using a shallow equality check, as the values seem to still be referentially stable.
> fix: Shallow equality check on cache parsing input

- packages/nuqs/src/debug.ts
- packages/nuqs/src/utils.ts
When in Safari set Block All cookies then local storage also will not work. But window.localStorage object itself will be available and when we will try set or get something from local storage we will get `SecurityError: The operation is insecure.` error and it is crashing the application for users with disabled cookies and local storage.
> fix: localStorage availability check update

- packages/nuqs/src/debug.ts
- packages/nuqs/src/utils.ts
Having the localStorage detection in a separate file was causing error logs in Vitest (no issues at runtime in Next.js).
This refactors the code to be more readable and maintainable, and into a single function so the enabled switch can now be const.
More of a refactoring than a bug fix, but it reduces the bundle size a little bit, so it warrants a patch update.
> fix: Move debug localStorage detection inline

- README.md
- packages/docs/content/docs/utilities.mdx
- packages/nuqs/package.json
- packages/nuqs/src/parsers.ts
- packages/nuqs/src/tests/parsers.test-d.ts
- pnpm-lock.yaml
> feat: Add parser type inference helpers

- packages/docs/content/docs/batching.mdx
- packages/e2e/cypress/e2e/useQueryStates-options.cy.js
- packages/e2e/src/app/app/useQueryStates-options/page.tsx
- packages/nuqs/src/update-queue.ts
- packages/nuqs/src/useQueryState.ts
- packages/nuqs/src/useQueryStates.ts
Order of precedence (first non-nullish wins):
- call level
- parser level
- hook-global level (otherwise default).
Also fixes a bug with `clearOnDefault` in useQueryState where a `true` top-level value could not be overriden by a call-level `false` value.
Closes #618.
> fix: Allow parser-level options in useQueryStates

- packages/docs/content/docs/batching.mdx
- packages/e2e/cypress/e2e/useQueryStates-clear-all.cy.js
- packages/e2e/src/app/app/useQueryStates-clear-all/page.tsx
- packages/nuqs/src/tests/compat/useQueryStates.test-d.ts
- packages/nuqs/src/tests/useQueryStates.test-d.ts
- packages/nuqs/src/useQueryStates.ts
By passing `null` instead of an object, every key managed by that`useQueryStates` hook will be cleared from the URL.
> feat: Allow clearing all search params managed by useQueryStates

- packages/e2e/cypress/e2e/repro-630.cy.js
- packages/e2e/src/app/app/repro-630/page.tsx
- packages/nuqs/src/useQueryStates.ts
The cache key for testing if the query changed wasn't being updated in `useQueryStates`.
This also revealed it being broken in `next@14.0.3`, where the history patching mechanism wasn't working. A fix has been added and will be removed in v2 (where support for those version ranges is dropped).
Closes #630.
> fix: Cache the query string in useQueryStates

- packages/e2e/cypress/e2e/repro-359.cy.js
- packages/nuqs/src/update-queue.ts
- packages/nuqs/src/useQueryState.ts
- packages/nuqs/src/useQueryStates.ts
- Follow the Rules of React to init the query ref once on mount
- Remove access to the queued value, doesn't seem to change
outcome of issue 359
> ref: Pure internal state init function

- packages/nuqs/src/serializer.test.ts
- packages/nuqs/src/serializer.ts
When using parsers in `createSerializer` it would not respect the `clearOnDefault` option properly when serializing, thus adding key-value pairs to the string that shouldn't be there.
An example:
```ts
const serialize = createSerializer({
int: parseAsInteger.withOptions({ clearOnDefault: true }).withDefault(0)
})
const result = serialize({ int: 0 })
//    ^ Result is `?int=0` instead of empty string
```
Closes https://github.com/47ng/nuqs/issues/641.
> fix: Serialization of default values in `createSerializer`

- packages/nuqs/src/serializer.test.ts
- packages/nuqs/src/serializer.ts
Follow-up to https://github.com/47ng/nuqs/discussions/646, that allows us to use the response from Next's `useSearchParams`, for example, as the `base` argument to a `serializer`. To do this we create a copy of `UrlSearchParams` in this code branch.
> fix(serializer): Allow serializers to operate on derived `UrlSearchParams` classes

- packages/e2e/src/app/app/cache/page.tsx
- packages/e2e/src/app/app/push/page.tsx
- packages/e2e/src/app/app/push/searchParams.ts
- packages/e2e/src/app/app/rewrites/destination/page.tsx
- packages/e2e/src/app/app/transitions/page.tsx
- packages/nuqs/src/cache.ts
- packages/nuqs/src/tests/cache.test-d.ts
Next.js 15.0.0-canary-171 introduced a breaking change in https://github.com/vercel/next.js/pull/68812 causing the searchParam page prop to be a Promise.
Using overloads, the cache.parse function can now handle either, but typing the searchParams page prop in userland is becoming painful if support for both Next.js 14 and 15 is desired.
Best approach is to always declare it as a Promise<SearchParams> (with `SearchParams` imported from 'nuqs/server'), as it highlights the need to await the result of the parser, and doesn't cause runtime issues if the underlyign type is a plain object (the await becomes a no-op).
> fix: Handle Promises for the searchParams page prop

- packages/docs/src/app/(pages)/_landing/dependents.tsx
Trying to reduce the amount of requests to Vercel, particularly the image optimisation bandwidth.
Images from GitHub are already sized the right way for a fixed target size.
> doc: Don't optimise dependents' avatars

- packages/nuqs/src/serializer.test.ts
- packages/nuqs/src/serializer.ts
Follow-up to https://github.com/47ng/nuqs/discussions/653, this PR allows callers to pass `null` to a serializer instance to clear any search params from `base`.
> feat(serializer): allow `null` to clear all param values from base

- .github/workflows/pkg.pr.new.yml
Added a conditional check in pkg.pr.new.yml to prevent unnecessary runs when no changes are detected in the nuqs package.
Closes #655.
> Fix: Run pkg.pr.new only if there are changes

- .github/workflows/pkg.pr.new.yml
This pull request refactors the CI workflow by splitting the process into two jobs: one for detecting changes in the nuqs package and another for deployment. The deployment now only runs when changes are detected, optimizing the CI pipeline and preventing unnecessary builds. Workflow logic was improved based on feedback to ensure proper communication between jobs.
- Added an ID to the step responsible for detecting changes in the `check-changes` job, allowing us to map the step output (`enable` flag) to a job-level output.
- Declared and passed the `enable` output at the job level for the `check-changes` job, ensuring proper communication between jobs.
- Updated the `deploy-preview` job to depend on the output of the `check-changes` job using the needs keyword. The deployment job now only …
> Refactor: Split pkg.pr.new into distinct check and deploy jobs

- packages/docs/content/docs/batching.mdx
- packages/e2e/cypress/e2e/remapped-keys.cy.js
- packages/e2e/src/app/app/remapped-keys/page.tsx
- packages/nuqs/src/tests/useQueryStates.test-d.ts
- packages/nuqs/src/useQueryStates.ts
While it was possible to do it via speading & remapping variable names in userland, this makes it more declarative and should help decouple business/domain logic in variable names vs short URL search param keys.
> feat: Allow remapping keys in useQueryStates

- .github/workflows/ci-cd.yml
- .github/workflows/test-against-nextjs-release.yml
This solves some incompatibilities when running tests related to the React version embedded by Next and exported by nuqs.
Symptom was that all pages in the pages router crashed on mount.
Supersedes #677, which attempted to use the catalogs feature of pnpm to keep things in sync, but isn't practical to inject custom versions in a CI context.
> chore: Install Next.js versions to both e2e & nuqs

- packages/nuqs/src/adapters/next/impl.pages.ts
Possible regression of #368.
Closes #693.
> fix: Add back the .js extension to the pages router adapter

- packages/nuqs/package.json
- pnpm-lock.yaml
TIL: all package managers download and install `optionalDependencies`. To mark them as optional peer, we need to leverage `peerDependenciesMeta.{packageName}.optional: true`.
Closes #696.
> fix: Mark framework packages as optional peer dependencies

- packages/adapters/react/src/components/search-input.tsx
- packages/adapters/remix/app/components/search-input.tsx
- packages/docs/src/app/playground/(demos)/tic-tac-toe/client.tsx
- packages/e2e/cypress/e2e/clearOnDefault.cy.js
- packages/e2e/src/app/app/clearOnDefault/page.tsx
- packages/e2e/src/app/app/remapped-keys/page.tsx
- packages/e2e/src/app/app/template/page.tsx
- packages/nuqs/src/defs.ts
- packages/nuqs/src/serializer.test.ts
- packages/nuqs/src/serializer.ts
- packages/nuqs/src/useQueryState.ts
- packages/nuqs/src/useQueryStates.ts
This should have made it in 2.0.0, but somehow slipped out of the net.
Since docs have already announced it, this is only a patch release, not a major update. May the SemVer gods forgive my sins.
Shout out to [@yasserconnect@x.com](https://x.com/yasserconnect/status/1848937299108630914) for fishing this out.
> fix: Make clearOnDefault: true by default

- packages/nuqs/esm-only.cjs
- packages/nuqs/package.json
The `eslint-import-resolver-alias` ESLint plugin chokes on nuqs adapters imports when running `next lint`:
```txt
Error while loading rule 'import/no-cycle': Package subpath './adapters/next/app' is not defined by "exports" in /[...]/node_modules/nuqs/package.json
```
Adding a stub CJS file for all exports that throws with a link to the original issue seems to satisfy the module resolution graph (the contents of the file aren't actually interpreted, but there needs to be one, `exports.*.require: null` doesn't cut it).
Closes #691.
> fix: Add stub CJS exports for old ESLint plugins

- packages/docs/content/docs/parsers/demos.tsx
I found the issue that on the docs Date inputs don't work well.
https://nuqs.47ng.com/docs/parsers/built-in#dates--timestamps
if we click `now` button, date successfully filled to the input and demo is working well, but if we it manually selecting the date and time, selected value is not filled.
This is because we can't `valueAsDate` for the input tag with `datetime-local`, so I fixed it.
I think this might be the same with the code below, but I don't know how I open the page of it so I can't debug it.
https://github.com/mehm8128/nuqs/blob/fix/docs-date-input/packages/docs/src/app/playground/_demos/parsers/page.tsx#L92-L109
> doc: Fix date inputs on Chrome

- packages/docs/content/docs/seo.mdx
- packages/nuqs/src/cache.ts
- packages/nuqs/src/defs.ts
- packages/nuqs/src/index.server.ts
- packages/nuqs/src/index.ts
- packages/nuqs/src/serializer.ts
- packages/nuqs/src/tests/serializer.test-d.ts
Update the SEO docs to reflect the change (and make it comprehensive)
> feat: Export the SearchParams type in both client & server bundles

- packages/docs/content/docs/testing.mdx
- packages/docs/mdx-components.tsx
- packages/nuqs/src/adapters/testing.ts
Add docs for both v1 & v2, using Fumadocs's code tab directives.
Closes #706.
> feat: Export OnUrlUpdateFunction type for Vitest v2

- packages/docs/content/docs/server-side.mdx
- packages/nuqs/src/cache.test.ts
- packages/nuqs/src/cache.ts
This bridges the API gap for this feature, along with #720 which defines it for the serializer.
Closes #679.
> feat: Add support for urlKeys in cache

- packages/docs/content/docs/utilities.mdx
- packages/nuqs/src/serializer.test.ts
- packages/nuqs/src/serializer.ts
> feat: Add urlKeys & clearOnDefault support for serializer

- packages/nuqs/src/adapters/next/impl.app.ts
on next 15 app router. I was getting an error when updating a search param in a form input event handler. wrapping setOptimisticSearchParams with startTransition fixed it
```ts
<Input
placeholder="https://example.com/font.woff2"
{...field}
onChange={(e) => {
setWebFontUrl(e.target.value);
field.onChange(e);
}}
/>
```
error
```
ConsoleError: An optimistic state update occurred outside a transition or action. To fix, move the update to an action, or wrap with startTransition.
at handleClientError (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.1_react-dom@19.0.0-rc-69d4b800-20241021_react@19.0.0-rc-69d4b800-20241021__react@19.0.0-rc-69d4b800-20241021/node_modules/next/dist/client/components/react-dev-overlay/internal/helpers/use-error-handler.js:41:17)
at …
```
> fix(adapters/next): wrap setOptimisticSearchParams in startTransition

- packages/docs/content/docs/troubleshooting.mdx
Components using hooks like useQueryState should be wrapped in `<Suspense>` when rendered within a page component. 
Fixes #496.
> doc: Updated docs Client Components to be Wrapped in a `<Suspense>` Boundry

- packages/nuqs/src/adapters/testing.ts
- packages/nuqs/src/update-queue.ts
This caused issues in sequential tests where a test would update a query state, the URL update would be queued, but not flushed at the moment when the test finished, and the next test would then pick up the queued value in its initial state.
> fix: Make the testing adapter clear the URL queue

- packages/nuqs/src/parsers.ts
- packages/nuqs/src/serializer.test.ts
- packages/nuqs/src/serializer.ts
- packages/nuqs/src/tests/serializer.test-d.ts
See [related discussion](https://github.com/47ng/nuqs/discussions/767).
Passing `null` to the serialize of a search param whose parser has a default currently is a type error, even though the behaviour works as expected.
This is because for the values argument it infers the types using the same `inferParserType` which is fine for parsing but is not quite right for serializing. The way i'm fixing it is just declaring a different `inferSerializerRecordType` to be used here. If there's some TS-foo i don't know which allows reusing the same `inferParserRecordType`, that'd be even better!
`CONTRIBUTING.md` mentions "adding a minimal reproduction in the playground can be very helpful" but i couldn't immediately find how to create one [there](https://nuqs.47ng.com/playground).
Added some very …
> fix(serializer/types): Allow `null` value in serializer for parsers with default values

- packages/e2e/next/cypress/e2e/repro-774.cy.js
- packages/e2e/next/src/app/app/repro-774/page.tsx
- packages/nuqs/src/useQueryStates.ts
This fixes an issue where `<Link>` navigation (or external updates of the URL) kept an internal stale state ref and reused it when updating other search params.
Closes #763, #774.
> fix: Update useQueryStates state cache when syncing from useSearchParams

- packages/docs/content/docs/testing.mdx
> docs: Document testing nuqs based hooks

- packages/nuqs/src/index.server.ts
- packages/nuqs/src/index.ts
Bonsoir!* This PR fixes a type issue _someone with my exact username_ 👀 introduced in #769, related to TypeScript.
It seems like TS has issues with inferring the type of the created serialized if it doesn't have access to the `Nullable` type, and I've been getting this very cryptic error:
```
The inferred type of 'serializeProductDetailParams' cannot be named without a reference to '@/node_modules/nuqs/dist/_tsup-dts-rollup'. This is likely not portable. A type annotation is necessary.
```
This PR solves this by simply exporting nuqs' `Nullable` type (for both client and server package entrypoints), if that's alright with you, and `Nullable` doesn't even have to be imported by app code to solve the TS issue.
I'm not sure why TS can't manage without this explicit export and from some …
> fix(types): Export `Nullable` type for correctly inferring return type of `createSerializer()`

- packages/nuqs/src/serializer.test.ts
- packages/nuqs/src/serializer.ts
> fix: Support `?` characters in serializer base

- packages/nuqs/src/cache.ts
- packages/nuqs/src/defs.ts
- packages/nuqs/src/parsers.ts
- packages/nuqs/src/serializer.ts
- packages/nuqs/src/tests/cache.test-d.ts
- packages/nuqs/src/tests/serializer.test-d.ts
- packages/nuqs/src/useQueryStates.ts
This helps defining the values for urlKeys in a type-safe manner by tying it to a parsers object.
```ts
import { type UrlKeys } from 'nuqs' // or 'nuqs/server'
export const coordinatesSearchParams = {
latitude: parseAsFloat.withDefault(0),
longitude: parseAsFloat.withDefault(0),
}
export const coordinatesUrlKeys: UrlKeys<typeof coordinatesSearchParams> = {
latitude: 'lat',
longitude: 'lng',
}
// Later in the code:
useQueryStates(coordinatesSearchParams, {
urlKeys: coordinatesUrlKeys
})
createSerializer(coordinatesSearchParams, {
urlKeys: coordinatesUrlKeys
})
createSearchParamsCache(coordinatesSearchParams, {
urlKeys: coordinatesUrlKeys
})
```
Note: the UrlKeys type is intentionally wider to work in useQueryStates, which does not (yet) use the ParsersMap also introduced in this PR. …
> feat: Add UrlKeys type helper

- packages/docs/content/docs/parsers/built-in.mdx
The options is located at https://nuqs.47ng.com/docs/options and not in https://nuqs.47ng.com/docs/parsers/options :)
> doc: Fix link to options docs

- packages/nuqs/src/adapters/lib/react-router.ts
To synchronise the server search params (from stock RR useSearchParams to the internal optimistic search params state).
Using a layout effect gives a warning:
```txt
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format.
This will lead to a mismatch between the initial, non-hydrated UI and the intended UI.
To avoid this, useLayoutEffect should only be used in components that render exclusively on the client.
See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
```
Looks like tests are passing fine with a good old useEffect (shallow would be the smoking gun here).
> ref: Use a useEffect rather than useLayoutEffect

- packages/docs/content/docs/options.mdx
- packages/e2e/react-router/v6/src/react-router.tsx
- packages/e2e/react-router/v7/app/root.tsx
- packages/e2e/remix/app/root.tsx
- packages/nuqs/src/adapters/lib/patch-history.ts
- packages/nuqs/src/adapters/lib/react-router.ts
- packages/nuqs/src/adapters/react-router.ts
- packages/nuqs/src/adapters/react-router/v6.ts
- packages/nuqs/src/adapters/react-router/v7.ts
- packages/nuqs/src/adapters/remix.ts
- packages/nuqs/src/useQueryState.ts
- packages/nuqs/src/useQueryStates.ts
It's needed to follow `<Link>` navigation, which is pretty essential.
Cleanup of tests made in #830.
> ref: Enable history patching by default for React Router

- packages/docs/content/docs/adapters.mdx
- packages/e2e/react-router/v6/cypress/e2e/repro-839.cy.ts
- packages/e2e/react-router/v6/src/react-router.tsx
- packages/e2e/react-router/v6/src/routes/repro-839.tsx
- packages/e2e/react-router/v7/app/routes.ts
- packages/e2e/react-router/v7/app/routes/repro-839.tsx
- packages/e2e/react-router/v7/cypress/e2e/repro-839.cy.ts
- packages/e2e/remix/app/routes/repro-839.tsx
- packages/e2e/remix/cypress/e2e/repro-839.cy.ts
- packages/e2e/shared/specs/react-router/repro-839-location-state-persistence.cy.ts
- packages/e2e/shared/specs/react-router/repro-839-location-state-persistence.tsx
- packages/nuqs/src/adapters/lib/react-router.ts
When using `shallow: false`, any user state set using `navigate('url', { state: whatever })` was reset to null.
Kind of a hack to read it from `history.state.usr`, but it seems to work without adding a `useLocation` dependency (which might cause loss of referential stability for the state updater function and possibly extra renders). However, this will limit it to the BrowserRouter, and not be compatible with the in-memory router (which wasn't compatible before anyway, and is unlikely to ever be).
Closes #839.
> fix: Maintain location.state in React Router frameworks

- packages/e2e/next/cypress/e2e/shared/render-count.cy.ts
- packages/e2e/next/package.json
- packages/e2e/next/src/app/app/(shared)/render-count/[hook]/[shallow]/[history]/[startTransition]/page.tsx
- packages/e2e/next/src/pages/pages/render-count/[hook]/[shallow]/[history]/[startTransition]/index.tsx
- packages/e2e/react-router/v6/cypress/e2e/shared/render-count.cy.ts
- packages/e2e/react-router/v6/src/react-router.tsx
- packages/e2e/react-router/v6/src/routes/render-count.$hook.$shallow.$history.$startTransition.async-loader.tsx
- packages/e2e/react-router/v6/src/routes/render-count.$hook.$shallow.$history.$startTransition.no-loader.tsx
- packages/e2e/react-router/v6/src/routes/render-count.$hook.$shallow.$history.$startTransition.sync-loader.tsx
- packages/e2e/react-router/v7/app/routes.ts
- packages/e2e/react-router/v7/app/routes/render-count.$hook.$shallow.$history.$startTransition.async-loader.tsx
- packages/e2e/react-router/v7/app/routes/render-count.$hook.$shallow.$history.$startTransition.no-loader.tsx
- packages/e2e/react-router/v7/app/routes/render-count.$hook.$shallow.$history.$startTransition.sync-loader.tsx
- packages/e2e/react-router/v7/cypress/e2e/shared/render-count.cy.ts
- packages/e2e/react/cypress/e2e/shared/render-count.cy.ts
- packages/e2e/react/src/routes.tsx
- packages/e2e/react/src/routes/render-count.tsx
- packages/e2e/remix/app/routes/render-count.$hook.$shallow.$history.$startTransition.async-loader.tsx
- packages/e2e/remix/app/routes/render-count.$hook.$shallow.$history.$startTransition.no-loader.tsx
- packages/e2e/remix/app/routes/render-count.$hook.$shallow.$history.$startTransition.sync-loader.tsx
- packages/e2e/remix/cypress/e2e/shared/render-count.cy.ts
- packages/e2e/shared/create-test.ts
- packages/e2e/shared/cypress.config.ts
- packages/e2e/shared/specs/render-count.cy.ts
- packages/e2e/shared/specs/render-count.params.ts
- packages/e2e/shared/specs/render-count.tsx
- packages/nuqs/src/adapters/lib/patch-history.ts
- packages/nuqs/src/adapters/next/impl.app.ts
- packages/nuqs/src/useQueryStates.ts
- turbo.json
The optimal number of renders should be:
- On mount: 1 (with the correct search params)
- On update, with shallow: true (the default): 2 (one for the internal state, and one when the URL has updated)
- On update, with shallow: false: 2 to 3, depending of whether we do optimistic URL updates and the time it takes for the server to respond and "update" the URL again
- `useQueryStates` now renders only once on mount (was 2 renders previously)
- `useQueryStates` now renders one less time (detecting query cache hits)
- Fixed a bug in the patch-history caching logic (for React Router & Remix), saving one extra render on `shallow: false`.
<details><summary>Baseline</summary>
```txt
app router - useQueryState - shallow: true, history: replace, startTransition: false should then render 2 times on …
```
> perf: Optimise render counts

- packages/nuqs/src/tests/useQueryStates.test-d.ts
- packages/nuqs/src/useQueryStates.test.ts
- packages/nuqs/src/useQueryStates.ts
This would allow conditionally clearing the URL based on the previous values.
Can't think of an immediately practical use-case, but when updating the type testing suite in #867, it felt like a blind spot in the API.
> fix: Allow useQueryStates' state updater function to return null

- packages/nuqs/src/useQueryStates.test.ts
- packages/nuqs/src/useQueryStates.ts
> fix: Dynamic keys for useQueryStates

- packages/e2e/next/cypress/e2e/shared/basic-io.cy.ts
- packages/e2e/next/src/app/app/agnostic/basic-io/page.tsx
- packages/e2e/next/src/app/app/agnostic/layout.tsx
- packages/e2e/next/src/pages/pages/agnostic/basic-io.tsx
- turbo.json
> test: Add test for the agnostic adapter

- packages/e2e/next/cypress/e2e/shared/conditional-rendering.cy.ts
- packages/e2e/next/src/app/app/(shared)/conditional-rendering/useQueryState/page.tsx
- packages/e2e/next/src/app/app/(shared)/conditional-rendering/useQueryStates/page.tsx
- packages/e2e/next/src/pages/pages/conditional-rendering/useQueryState.tsx
- packages/e2e/next/src/pages/pages/conditional-rendering/useQueryStates.tsx
- packages/e2e/react-router/v6/cypress/e2e/shared/conditional-rendering.cy.ts
- packages/e2e/react-router/v6/src/react-router.tsx
- packages/e2e/react-router/v6/src/routes/conditional-rendering.useQueryState.tsx
- packages/e2e/react-router/v6/src/routes/conditional-rendering.useQueryStates.tsx
- packages/e2e/react-router/v7/app/routes.ts
- packages/e2e/react-router/v7/app/routes/conditional-rendering.useQueryState.tsx
- packages/e2e/react-router/v7/app/routes/conditional-rendering.useQueryStates.tsx
- packages/e2e/react-router/v7/cypress/e2e/shared/conditional-rendering.cy.ts
- packages/e2e/react/cypress/e2e/shared/conditional-rendering.cy.ts
- packages/e2e/react/src/routes.tsx
- packages/e2e/react/src/routes/conditional-rendering.useQueryState.tsx
- packages/e2e/react/src/routes/conditional-rendering.useQueryStates.tsx
- packages/e2e/remix/app/routes/conditional-rendering.useQueryState.tsx
- packages/e2e/remix/app/routes/conditional-rendering.useQueryStates.tsx
- packages/e2e/remix/cypress/e2e/shared/conditional-rendering.cy.ts
- packages/e2e/shared/specs/conditional-rendering.cy.ts
- packages/e2e/shared/specs/conditional-rendering.tsx
- packages/nuqs/src/adapters/lib/react-router.ts
> fix: Conditional rendering in React Router

- packages/docs/content/docs/troubleshooting.mdx
Updating the wording of [Client components need to be wrapped in a <Suspense> boundary](https://nuqs.47ng.com/docs/troubleshooting#client-components-need-to-be-wrapped-in-a-suspense-boundary) section based on the discussion at https://github.com/47ng/nuqs/discussions/846
> doc: Update wording for the "missing suspense boundary" guidelines

- demo-tabs.tsx
- packages/docs/content/docs/basic-usage.mdx
- packages/docs/src/app/(pages)/_landing/demo.client.tsx
- packages/docs/src/app/(pages)/_landing/demo.tsx
> doc: add break word all for better ux

- packages/e2e/shared/specs/conditional-rendering.cy.ts
- packages/nuqs/src/adapters/lib/react-router.ts
- packages/nuqs/src/adapters/react-router/v6.ts
- packages/nuqs/src/adapters/react-router/v7.ts
- packages/nuqs/src/adapters/remix.ts
It looks like `useSearchParams`' `defaultInit` argument is cached on the first call and not re-evaluated when mounting subsequent components, causing those re-mounted components to have a stale optimistic search params state.
Closes #881.
> fix: React Router stale values after remount

- packages/e2e/react-router/v6/cypress/e2e/shared/fog-of-war.cy.ts
- packages/e2e/react-router/v6/src/react-router.tsx
- packages/e2e/react-router/v6/src/routes/fog-of-war._index.tsx
- packages/e2e/react-router/v6/src/routes/fog-of-war.result.tsx
- packages/e2e/react-router/v7/app/routes.ts
- packages/e2e/react-router/v7/app/routes/fog-of-war._index.tsx
- packages/e2e/react-router/v7/app/routes/fog-of-war.result.tsx
- packages/e2e/react-router/v7/cypress/e2e/shared/fog-of-war.cy.ts
- packages/e2e/remix/app/routes/fog-of-war._index.tsx
- packages/e2e/remix/app/routes/fog-of-war.result.tsx
- packages/e2e/remix/cypress/e2e/shared/fog-of-war.cy.ts
- packages/e2e/shared/specs/react-router/fog-of-war.cy.ts
- packages/e2e/shared/specs/react-router/fog-of-war.tsx
> test: Add React Router Fog of War test

- packages/nuqs/tests/cache.test-d.ts
- packages/nuqs/tests/parsers.test-d.ts
- packages/nuqs/tests/serializer.test-d.ts
- packages/nuqs/tests/useQueryState.test-d.ts
- packages/nuqs/tests/useQueryStates.test-d.ts
- packages/nuqs/tsconfig.build.json
There is no need for them to be in src since they test against the built types in dist.
Moving them out cleans it all up and allows for shorter relative import paths.
> chore: Move type tests away from src

- packages/nuqs/package.json
Somehow these slipped out of the `files` definition, doesn't seem to have caused issues but added back for consistency.
> fix: Ship react-router v6/v7 .d.ts redirects on NPM

- packages/docs/src/app/playground/_demos/repro-907/page.tsx
- packages/nuqs/src/useQueryStates.test.ts
- packages/nuqs/src/useQueryStates.ts
> fix: useQueryStates does not update values correctly when config changes

- packages/e2e/next/cypress/e2e/shared/scroll.cy.ts
- packages/e2e/next/src/app/app/(shared)/scroll/page.tsx
- packages/e2e/next/src/pages/pages/scroll.tsx
- packages/e2e/react-router/v6/cypress/e2e/shared/scroll.cy.ts
- packages/e2e/react-router/v6/src/react-router.tsx
- packages/e2e/react-router/v6/src/routes/scroll.tsx
- packages/e2e/react-router/v7/app/routes.ts
- packages/e2e/react-router/v7/app/routes/scroll.tsx
- packages/e2e/react-router/v7/cypress/e2e/shared/scroll.cy.ts
- packages/e2e/react/cypress/e2e/shared/scroll.cy.ts
- packages/e2e/react/src/routes.tsx
- packages/e2e/react/src/routes/scroll.tsx
- packages/e2e/remix/app/routes/scroll.tsx
- packages/e2e/remix/cypress/e2e/shared/scroll.cy.ts
- packages/e2e/shared/cypress.config.ts
- packages/e2e/shared/specs/scroll.cy.ts
- packages/e2e/shared/specs/scroll.tsx
- packages/nuqs/src/adapters/react.ts
Adding a test for #912 surfaced that the scroll option wasn't implemented for the React SPA adapter.
Closes #912.
> feat: Add scroll option support for React SPA adapter

- packages/nuqs/src/debug.test.ts
- packages/nuqs/src/debug.ts
In some cases (can't reproduce it reliably though), turning on debug logs and logging console.log('%s', null) will throw an error due to this line in React Devtools: 
https://github.com/facebook/react/blob/f83903bfcc5a61811bd1b69b14f0ebbac4754462/packages/react-devtools-shared/src/backend/utils/formatConsoleArguments.js#L59-L61
PR fixing it: https://github.com/facebook/react/pull/32372.
Falling back to the flattened message if the overloaded console.log fails.
Closes #808.
> fix: Handle console.log of null values in React Devtools

- errors/NUQS-303.md
- errors/NUQS-404.md
- packages/nuqs/src/adapters/lib/context.ts
- packages/nuqs/src/debug.ts
- packages/nuqs/src/errors.ts
> feat: Detect multiple contexts loaded at the same time

- .github/workflows/pkg.pr.new.yml
- packages/nuqs/remove-me
- ~Add intro ("Use this to install a preview build of this PR" or something)~
Any customisation of the comment requires a complete opt-out of the automated behaviour and maintaining the code that does this work ourselves, we might need to think about a better way and contribute that to pkg.pr.new.
See https://github.com/stackblitz-labs/pkg.pr.new/issues/263
> chore: Update pkg.pr.new comments

- .github/workflows/ci-cd.yml
- packages/docs/content/docs/adapters.mdx
- packages/e2e/react/src/main.tsx
- packages/e2e/react/vite.config.ts
- packages/nuqs/src/adapters/react.ts
- turbo.json
This allows using the React SPA adapter with a backend server catching the search param updates configured with `shallow: false`. For example, this can be useful when paired with a server written in other languages than JavaScript: Rails, Laravel, Django, Phoenix etc, that serves a statically built React SPA bundle.
It's disabled by default to keep compatibility with existing code (where `shallow: false` doesn't do anything), but it might be switched on by default in nuqs@3.0.0 (TBC).
```tsx
import { NuqsAdapter } from 'nuqs/adapters/react'
import { createRoot } from 'react-dom/client'
createRoot(document.getElementById('root')!).render(
<NuqsAdapter reloadPageOnShallowFalseUpdates>
<App />
</NuqsAdapter>
)
```
- ~Do a test with Django or Phoenix~
> feat: Full-page navigation option for `shallow: false` updates in React SPA

- packages/docs/content/docs/parsers/built-in.mdx
- packages/docs/content/docs/parsers/demos.tsx
- Add pagination UI
- Show the internal state
- Clarify in which direction the +/-1 occurs
> doc: Fix the parseAsIndex demo

- packages/nuqs/src/cache.ts
Having `import { cache } from 'react'` caused issues when using React 18 or 19 GA, because the `cache` function is only exported in canary builds (which the Next.js app router uses internally, regardless of what's in your app's package.json).
This meant importing from `'nuqs/server'` caused an import error when done from non app-router code, like the pages router, an API route definition, or a non-Next.js framework, which would fallback to the version of React defined in the package.json (likely a stable one).
Changing the import to `import * as React from 'react'` is what is being highlighted in the React docs themselves, and allows to only call the cache function when actually creating a cache object.
Closes #804, and supersedes #805.
> fix: Import React.cache only when needed

- packages/nuqs/src/cache.ts
- packages/nuqs/src/defs.ts
- packages/nuqs/src/parsers.ts
- packages/nuqs/src/useQueryStates.ts
Using Matt Pocock's [Prettify helper](https://www.totaltypescript.com/concepts/the-prettify-helper), we can resolve the underlying parsed data types in derived features like the loaders, cache, serializers etc, rather than getting gnarly half-resolved types based on the parser types.
Demo: https://www.youtube.com/watch?v=nlAPCgMfPXY
> fix: Prettify inferred types

- packages/docs/content/docs/community-adapters/waku.mdx
useRouter is no longer unstable in Waku since v0.22.
> chore(docs): Waku v0.22 community adapter useRouter update 

- packages/nuqs/src/adapters/next/impl.app.ts
So that the agonostic adapter is happy about the import when bundled under the pages router.
Closes #869.
> fix: Import from next/navigation.js

- .github/workflows/ci-cd.yml
- .github/workflows/test-against-nextjs-release.yml
- packages/e2e/next/package.json
- pnpm-lock.yaml
Add it to the CI process, pruning some of the basePath checks as those seem to be stable between versions (only checking minors).
> chore: Use React Compiler RC

- README.md
- packages/docs/content/docs/options.mdx
Docs appear to be incorrect, parsers aren't functions that can be called like this
> doc: Fix transition docs to not call parser as function

- packages/docs/src/app/globals.css
Fix title is hidden behind headers on mobile
from: 
to:
Closes #1042.
> doc: Title is hidden behind headers on mobile

- packages/docs/src/app/playground/(demos)/pagination/rendering-controls.tsx
a small fix to prevent `NaN` from appearing in the URL query. When the toggled state is off, the `onValueChange` callback receives an empty string, which is parsed as `NaN`.
> doc: prevent NaN appearing in pagination example

- packages/e2e/shared/specs/stitching.tsx
- packages/nuqs/package.json
- packages/nuqs/src/adapters/lib/patch-history.ts
- packages/nuqs/src/adapters/lib/react-router.ts
- packages/nuqs/src/adapters/react.ts
- packages/nuqs/src/lib/compose.ts
- packages/nuqs/src/lib/debug.ts
- packages/nuqs/src/lib/emitter.test.ts
- packages/nuqs/src/lib/emitter.ts
- packages/nuqs/src/lib/queues/debounce.ts
- packages/nuqs/src/lib/queues/throttle.ts
- packages/nuqs/src/lib/queues/useSyncExternalStores.test.ts
- packages/nuqs/src/lib/sync.ts
- packages/nuqs/src/lib/with-resolvers.ts
- packages/nuqs/src/loader.ts
- packages/nuqs/src/parsers.ts
- packages/nuqs/src/useQueryState.ts
- pnpm-lock.yaml
Various little refactorings here and there to reduce the minified + gzipped bundle size.
Notable changes:
- Replaced `mitt` with a smaller emitter bus (we didn't need the '*' event in mitt). nuqs is now a zero-runtime-dependency library! 🙌
- Removed the implementation of useQueryState to use useQueryStates internally
Ideally if we could land under 5kB that would be amazing, but short of removing all the debug log points, it would likely make the code hard to read and/or maintain.
Reduction: 5.943kB → 5.48kB (-463B, ~8%)
> chore: Reduce the bundle size

- packages/nuqs/src/lib/queues/rate-limiting.ts
- packages/nuqs/src/lib/queues/throttle.test.ts
- packages/nuqs/src/lib/queues/throttle.ts
Some operations are not allowed at the top level in CloudFlare Workers, which includes creating an AbortController.
Since the global throttle queue is a singleton, it gets bundled up in the server bundle and causes this issue.
We now lazily create that controller on the first call to `flush`, when it becomes needed.
Fixes #1091.
> fix: Lazily create AbortController in throttle queue for CloudFlare Workers support

- package.json
- pnpm-lock.yaml
From the deployment logs:
```txt
[@octokit/request] "GET https://api.github.com/search/issues?q=in%3Atitle+repo%3A47ng%2Fnuqs+type%3Aissue+state%3Aopen+The%20automated%20release%20is%20failing%20%F0%9F%9A%A8" is deprecated. It is scheduled to be removed on Thu, 04 Sep 2025 00:00:00 GMT. See https://github.blog/changelog/2025-03-06-github-issues-projects-api-support-for-issues-advanced-search-and-more/
```
Reference: https://www.github.com/semantic-release/github/issues/1022
> chore: Use semantic-release/github 11.0.5 to handle deprecated search endpoints

- packages/docs/content/docs/options.client.tsx
- packages/docs/content/docs/options.mdx
- packages/nuqs/src/adapters/lib/context.ts
- packages/nuqs/src/adapters/testing.ts
- packages/nuqs/src/lib/queues/throttle.test.ts
- packages/nuqs/src/lib/queues/throttle.ts
- packages/nuqs/src/useQueryStates.test.ts
- packages/nuqs/src/useQueryStates.ts
- turbo.json
> feat: Add processUrlSearchParams middleware as adapter prop

- .github/workflows/pkg.pr.new.yml
When opening a PR from the GitHub Pull Request extension in VSCode, I typically label it and add milestones before opening it. This triggers two "PR Preview" workflows simultaneously:
1. One for the `pull_request opened` event
2. One for the `pull_request labeled` event
This causes a race condition where `pkg-pr-new publish` runs twice, sometimes resulting in duplicate comments being posted to the PR instead of updating the existing comment.
Updated the concurrency configuration to prevent race conditions while maintaining efficiency:
- **Changed concurrency group** from SHA-based to PR number-based (`pkg-pr-new-${{ github.event.pull_request.number }}`)
- **Set `cancel-in-progress: false`** to queue workflows sequentially instead of cancelling them
- **Removed the artificial delay** that …
> chore: Prevent parallel runs of pkg.pr.new within a PR

- packages/nuqs/package.json
- turbo.json
Split size-limit operations into two separate scripts:
1. `build:size-json` - Only generates `size.json` for docs
2. `test:size` - Only validates size thresholds
Update `turbo.json` to:
- Remove `size.json` from `nuqs#build` outputs
- Add `nuqs#build:size-json` task
- Make `docs#build` depend on `nuqs#build:size-json`
- Removed postbuild script that ran `size-limit --json > size.json`
- Added `build:size-json` script: `size-limit --json > size.json`
- Kept `test:size` script: `size-limit` (for validation)
- Removed `size.json` from `nuqs#build` outputs
- Added `nuqs#build:size-json` task with `dependsOn: ["build"]`
- Updated `docs#build` dependsOn to include `nuqs#build:size-json`
- ✅ `pnpm turbo run docs#build` succeeds with proper task order:
- `nuqs:build` → generates dist/
- …
> chore: split size-limit script from build process
